global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: monk
    static_configs:
      - targets: ['monk-exporter:9090']
    scrape_interval: 15s
    metrics_path: /metrics
